title: "Sitio del Curso de Informática 10mo"
description: "Materiales, dosificación y recursos para estudiantes de Informática de 10mo grado del IPU Julio Antonio Mella McPartland"
email: "martinell.reynaldo@gmail.com"
baseurl: ""
url: "https://jmmartinell.github.io"

theme: jekyll-theme-hacker

collections:
  clases:
    output: true
    permalink: /clases/:name.html
  notas:
    output: true
    permalink: /notas/:name.html
  preguntas:
    output: true
    permalink: /preguntas/:name.html

defaults:
  - scope:
      path: "_clases"
      type: "clases"
    values:
      layout: "default"
  - scope:
      path: "_notas"
      type: "notas"
    values:
      layout: "default"
  - scope:
      path: "_preguntas"
      type: "preguntas"
    values:
      layout: "default"