title: "Sitio del Profesor José Manuel Martinell"
description: "Materiales, dosificación y recursos para estudiantes de Informática"
email: "jmmartinell@ejemplo.com"  # Reemplaza con tu email real
baseurl: ""
url: "https://jmmartinell.github.io"

theme: jekyll-theme-hacker

collections:
  clases:
    output: true
    permalink: /clases/:name.html
  notas:
    output: true
    permalink: /notas/:name.html
  preguntas:
    output: true
    permalink: /preguntas/:name.html

defaults:
  - scope:
      path: "_clases"
      type: "clases"
    values:
      layout: "default"
  - scope:
      path: "_notas"
      type: "notas"
    values:
      layout: "default"
  - scope:
      path: "_preguntas"
      type: "preguntas"
    values:
      layout: "default"